name: android
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ./gradlew buildDebug
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: soundcrowd-plugin-youtube.apk
          path: youtube/build/outputs/apk/debug/youtube-debug.apk
